### ISSUE TITLE
Create proper CLI

### ISSUE THREAD

**Issue by spion** [typed-graphql-builder/typed-graphql-builder#1]
Probably with `yargs` since it has reasonable type definitions.

**Comment by lubeskih** [comment]
@spion add more detailed info on this one.

**Comment by spion** [comment]
yargs bit is already done, now we need to: 
- [ ] move the yargs parsing out of the main function aind into `cli.ts` 
- [ ] extract the rest as a function with the yargs arguments,  
- [ ] create `bin` entry in package json pointing to the compiled cli.js

**Comment by spion** [comment]
Yargs main in `cli.ts` would look something like

function main() { 
  let args = yargs(...).argv; 
  let output = compileToTypescript(args); 
  fs.writeFileSync(args.outputFile, output); 
}

and everything else in the current main will go into `compileToTypescript`
