### ISSUE TITLE
Nested query variable type is not inferred

### ISSUE THREAD

**Issue by eliaharris** [typed-graphql-builder/typed-graphql-builder#18]
Going to investigate and see what's going on, but I think there may be a problem with how the variables are being inferred for nested queries.

An example query (some of the query)

<img width="744" alt="Screen Shot 2022-08-24 at 5 23 45 PM" src="https://user-images.githubusercontent.com/1924716/186526324-e5a1949f-a813-4c4c-bbb6-2665befecb7e.png">

And no TypeScript validation errors... The inference thinks "variables" is an empty object.

<img width="407" alt="Screen Shot 2022-08-24 at 5 25 06 PM" src="https://user-images.githubusercontent.com/1924716/186526501-0022b8ff-38e3-45b8-a6ba-bb046719f4fb.png">

Edit: After some digging, it appears that `GetVariables` is **not** recursive, so it's only going to pull the top-level arguments. I could be reading it wrong as I'm still getting familiar with the code base.

**Comment by eliaharris** [comment]
I have confirmed that all top-level variables are inferred just fine.

**Comment by spion** [comment]
I'm not sure if... "nestedness" is the problem - for example there is a test in `tests/examples/test-zeus.good.ts` which contains nested variables:

```typescript
let tq = query(q => [
  q.cardById({ cardId: $('cid') }, c => [
    ...cardFragment,
    c.attack({ cardID: $('cids') }, aCards => [
      aCards.Attack, //
      aCards.Defense,
    ]),
  ]),
...
```

**Comment by eliaharris** [comment]
On my machine, the query you listed does work 👍 

However, I was able to reproduce a case where the variables were not inferred.

Can you try this query and see if you don't get the variables inferred?

```typescript

const tq = query(q => [
  q.drawCard(c => [
    c.attack({cardID: $('cardID')}, s => [
        s.name
    ])
  ])
])```

**Comment by eliaharris** [comment]
This fixed it for me: https://github.com/typed-graphql-builder/typed-graphql-builder/pull/19

**Comment by spion** [comment]
Awesome, thank you! merged.

**Comment by spion** [comment]
Fix merged and published. Huge thanks again!
