### ISSUE TITLE
Enums & array inputTypes

### ISSUE THREAD

**Issue by ilijaNL** [typed-graphql-builder/typed-graphql-builder#20]
Hello, 
Firstly thanks for this awesome library. I really like the builder style syntax, in my opinion this is much cleaner than zeus for example. 

I got several problems on using this with hasura graphql:
- The order by enum is parsed as string instead of a enum value: 
```ts
import { query, order_by, $ } from '@/__generated__/api';
 query((q) => [
 q.organisations({ order_by: [{ name: order_by.asc_nulls_last }] }, (o) => [
    o.id,
    o.name,
    o.slug,
    o.subscription((s) => [s.plan, s.status]),
  ]),
]);
``` 
will be parsed into:
```ts
organisations(order_by: [{name: "asc_nulls_last"}]) {
    id
    name
    slug
    subscription {
      plan
      status
    }
  }
```
- Secondly when I try to use order_by as an variable inside the order_by array like this:
```ts
query((q) => [
  q.organisations({ order_by: [{ name: $('order_by_name')}] as const }, (o) => [
    o.id,
    o.name,
    o.slug,
    o.subscription((s) => [s.plan, s.status]),
  ]),
]);
```
I get typescript circularly references error. The reason is probably due the circular relationships, for eg: organisations -> subscriptions -> organisations.

Only possible solution is to make the whole order_by as a variable:
```ts
query((q) => [
  q.organisations({ order_by: $('order_by') }, (o) => [
    o.id,
    o.name,
    o.slug,
    o.subscription((s) => [s.plan, s.status]),
  ]),
])
```
But this is not optimal

- Additionally, I wonder how I can mark a variable nullable or not nullable and have an possible union.

I think many of these problems of inputTypes could be solved when the user must explicity define the type:

```ts
q.organisations({ order_by: [{ name: $('order_by_name', 'order_enum!')}] }, (o) => [
    o.id,
    o.name,
    o.slug,
    o.subscription((s) => [s.plan, s.status]),
  ]),
```
And apply the type match that makes ts happy. So when providing $('order_by_name', 'String!') typescript will complain.

Thanks

**Comment by spion** [comment]
Hi @ilijaNL 

Thanks for reporting the problem. 

I believe I found a fix for both of your issues, available here: https://github.com/typed-graphql-builder/typed-graphql-builder/pull/21 

Could you please look at it (especially the tests) and let me know if it looks good from your side? If so I'll merge and publish a new release

P.S. It looks like TS doesn't give good error messages when the types are recursive but its possible to debug with a non-recursive version of the type which is how I went about it

P.P.S. The ability to specify explicit variable types sounds like an interesting feature, and so does controlling nullability / optionality. Will give it some thought.

**Comment by ilijaNL** [comment]
@spion Thanks for the quick response. I checked your pr's, the enums seems to work. Next I left some comments on the #22  PR.
