### ISSUE TITLE
feat: support query and mutation extends

### ISSUE THREAD

**Issue by lrstanley** [typed-graphql-builder/typed-graphql-builder#25]
One feature that looks to be missing with typed-graphql-builder is the ability to use queries and mutations that were added as an `extend` on top of the existing `Query` and `Mutation` types.

My application, as an example, generates graphql schema files for most of the functionality, and there are some features that are manually implemented. Given the code generation generates the `Query` type (as an example), it can't be easily updated without being overwritten. As such, I use the `extend` feature to add additional queries and mutations to those base types, e.g:

```graphql
# file: base.gql -- has all generated schemas.
# [...]

# file: custom.gql -- custom extensions.
extend type Query {
    githubUser: GithubUser!
}

extend type Mutation {
    createPost(input: CreatePostInput!): Post!
    updatePost(id: ID!, input: UpdatePostInput!): Post!
    deletePost(id: ID!): ID!
    regeneratePosts: Boolean!
}
```

These are currently not picked up by typed-graphql-builder, and thus don't exist inside of the generated typescript file.

**Comment by lrstanley** [comment]
Looks like no `extends` features are currently supported (for scalars, enums, etc), as I don't see any of the extension types being referenced from graphql-js. For example, specifically for `Query`, this is what it looks like:

```
{
  kind: 'ObjectTypeExtension',
  name: { kind: 'Name', value: 'Query', loc: [Location] },
  interfaces: [],
  directives: [],
  fields: [ [Object] ],
  loc: Location {
    start: 1712,
    end: 1765,
    startToken: [Token],
    endToken: [Token],
    source: [Source]
  }
}
```

I was going to PR a fix, however it looks like it won't be as easy as I thought, given it's much more than just `Query` and `Mutation`.

Also, might be good to change this:

```typescript
  let res = gq.parse(schemaString)
```

to:

```typescript
  let res = gq.parse(schemaString, { noLocation: true })
```

if no location/line information is needed -- seems to make things quite a bit faster when parsing on my machine (it also mentions performance as a reason for adding that field in the docs).

**Comment by spion** [comment]
Yes, the code will need substantial changes to implement this, the current "streaming" approach without an intermediate representation won't quite work

However, a bit of cleanup and refactoring is needed anyway, so that would be a good opportunity to do the switch.

Also, big thanks for the performance tip - I'll try to make use of it.

**Comment by spion** [comment]
Hey @lrstanley I have a prototype implementation for this feature, would you mind having a look, especially in regards to what kind of API would be best suited for this feature?

(The reason I'm leaning towards the glob is because I've seen Apollo docs that recommend splitting schemas into multiple files, but I don't know how commonplace that is)

note: I haven't done the refactor / cleanup yet, sorry :sweat_smile:

**Comment by lrstanley** [comment]
My specific use case is actually multiple gql files, and I believe each time I was testing before, I was merging them all into one when passing them to the tool. Both options 2 and 3 I feel should be supported options (option 1 is too tedious IMO).

> need extra logic to auto-exclude original schema from globs

What is this referring to exactly?

I will test the PR out shortly and let you know.

**Comment by lrstanley** [comment]
Successfully tested, after building locally, running something to the effect of:

```console
$ cat ../../../internal/database/graphql/schema/*.gql | node ./typed-graphql-builder/dist/cli.js --schema - --output src/lib/api-new/graphql.ts
```

And used that to run a `query` that was `extend`ed. Confirmed all my usecases of extend are currently satisfied (mainly `query` and `mutation`).

--------------------

I do have an additional question, and this isn't specific to this issue (can open a new issue if you'd like), but more that this is one of the first TypedDocumentNode libraries I've used (coming from `@graphql-codegen/*` libraries) -- is there a relatively simple way of referencing the result type of queries built with TypedDocumentNode? I ask because I generally define queries in one location, and pass those throughout my application, and would like a way of restricting types (in a relatively sane way) between various components within the application.

For example, this is one of the queries I have today, that fetches information about the logged-in user, and what guilds (discord) they may have access to:

```graphql
query base {
    self {
        id
        admin
        username
        discriminator
        avatarURL

        userGuilds(first: 200, orderBy: { direction: DESC, field: NAME }) {
            edges {
                node {
                    id
                    guildID
                    name
                    iconURL
                    joinedAt

                    guildConfig {
                        enabled
                    }

                    guildAdminConfig {
                        enabled
                    }
                }
            }
        }
    }
}
```

I rewrote a portion of this to use this library, just to see how I can maintain the return types of those queries.


In the below example, I'm using urql (`@urql/vue` specifically) with a subset of the above query for testing:

```typescript
import { GuildOrderField, OrderDirection, query } from "@/lib/api-new/graphql"

export const baseQuery = query((q) => [
  q.self((u) => [
    u.id,
    u.admin,
    u.username,
    u.discriminator,
    u.avatarURL,
    u.userGuilds(
      {
        first: 200,
        orderBy: { direction: OrderDirection.DESC, field: GuildOrderField.NAME },
      },
      (g) => [g.edges((e) => [e.node((n) => [n.id, n.name])])]
    ),
  ]),
])
```

And consuming it like so:

```typescript
import { baseQuery } from "@/lib/api-new"
import { useQuery } from "@urql/vue"

const result = useQuery({ query: baseQuery })

// testing (array of Guild[]) would be a subset of the "Guild" type that gets generated.
const testing = computed(() => {
  return result.data.value?.self.userGuilds.edges.map(({ node }) => node)
})
```

Is there a way to export a type that is a selection-set of a given type mapping from the GraphQL schema? This way, with the above example, I could pass `testing` to another component/module that is expecting Guild[] (or at least a selection-set of it). In `@graphql-codegen`, I'm able to use the base `Guild` type, as the fields are all defined as optional, and thus the result type (which may be a sub-set of the fields) can be cast to the base type.

**Comment by spion** [comment]
Its a fair question.

You can use the helper type `ResultOf` on queries on `TypeDocumentNode` queries. (We should probably add this to the docs)

```
import { ResultOf } from '@graphql-typed-document-node/core';
import { query } from './api.ts';

const myQuery = query(...);
type MyQueryResult = ResultOf<typeof myQuery>
```

Unfortunately typed-graphql-builder doesn't yet export full output object types or a helper to get those. That seems useful to add. Here is a generic approach to it

```
export type OutputTypeOf<T> = T extends $Base<any>
  ? { [K in keyof T]?: OutputTypeOf<T[K]> }
  : [T] extends [$Field<any, infer FieldType, any>]
  ? FieldType
  : [T] extends [(selFn: (arg: infer Inner) => any) => any]
  ? OutputTypeOf<Inner>
  : [T] extends [(args: any, selFn: (arg: infer Inner) => any) => any]
  ? OutputTypeOf<Inner>
  : never
```

**Comment by lrstanley** [comment]
Thanks -- will give that a try later today!

**Comment by spion** [comment]
Publishing extends support in 3.0.0 (bumped version due to change of library API function name)

Will add `OutputTypeOf` to the exports in 3.1.0.

**Comment by lrstanley** [comment]
Awesome, just tested `OutputTypeOf` and it's sufficient enough for my usecase.

Going to close this issue out, however, might be worth making another for the other missing extend types.
