### ISSUE TITLE
Object Variable Type

### ISSUE THREAD

**Issue by eliaharris** [typed-graphql-builder/typed-graphql-builder#33]
Hello,

I'm not sure what happened, but upgrading from `2.1.0` to `2.2.0` or greater is now giving me errors for my input types that are objects:

![Screen Shot 2022-09-28 at 11 11 59 AM](https://user-images.githubusercontent.com/1924716/192818465-a34f3185-6597-4103-b8af-58b0f057ffb2.png)

It appears that it cannot infer the `Type` for the `VariabledInput` generic. I'll do some digging. It appears `VariabledInput` was heavily changed, so I bet it's something in there.

**Comment by spion** [comment]
Hi @eliaharris does this still persist in v2.2.3 or greater?

I think the issue was https://github.com/typed-graphql-builder/typed-graphql-builder/issues/29 and fixed with the v2.2.3 release

**Comment by eliaharris** [comment]
Sorry, you are right @spion. I goofed and thought I had the latest version

**Comment by eliaharris** [comment]
Need to remember to keep my fork updated... 😆
