### ISSUE TITLE
Inline Fragment Support

### ISSUE THREAD

**Issue by jakobo** [typed-graphql-builder/typed-graphql-builder#36]
Ran into this issue migrating a personal project that uses the GitHub API. It seems that the inline fragments (implementations) on the `GitObject` aren't getting properly exposed. I suppose I expected to see `x.$on` or `x.$as` in the example.

**edit** After digging into GitHub's schema, they rely on returning the `GitObject` interface from `repository().object()` which can then be cast to one of `Blob`, `Tree`, `Commit`, `Tag`. After digging through the GraphQL resources, this [is a feature](https://graphql.org/learn/queries/#inline-fragments) of GraphQL. If a query/mutation returns an interface, then you can request any of the polymorphic casts of that interface.

Schema: https://api.github.com/graphql (or download at https://docs.github.com/en/graphql/overview/public-schema)

```gql
# GraphQL Query
query SelectObjectContents {
  repository(name: "codedrift", owner: "jakobo") {
    object(expression: "main:src/data/manifest.yaml") {
      ... on Blob {
        id
        text
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/1795/195221591-fb93d40d-ed2c-428e-9320-3e65ca084555.png)

Finally, given our other conventions around unions, I suppose this is how I expected the polymorphism to be exposed.

```ts
export const selectShortlinkData = query((q) => [
  q.repository({ name: "codedrift", owner: "jakobo" }, (r) => [
    r.object({ expression: "main:src/data/shortlinks.yaml" }, (o) => [
      o.id,
      o.$on("Blob", (b) => [b.text]),
    ]),
  ]),
]);
```

**Comment by jakobo** [comment]
Did additional digging this morning to see if we can do this w/o adding yet-another-schema to the examples. I was able to replicate locally using the [star wars api](https://github.com/typed-graphql-builder/typed-graphql-builder/blob/main/test/examples/sw.graphql), since the root `node()` returns the interface `Node` and should allow for polymorphism.

```gql
query {
  node(id: "sample") {
    ... on Person {
      id
      name
    }
  }
}
```

I'll see if I can at the very least make a PR demonstrating the failing test case as `test-sw.bad.ts`; still wrapping my head around `compile.ts`.

**Comment by spion** [comment]
Thanks, a test case will be very helpful.

**Comment by jakobo** [comment]
Done in #37. All tests pass since the current implementation is marked as failing `test-fragments-sw.bad.ts`
