### ISSUE TITLE
operationName configuration

### ISSUE THREAD

**Issue by awinograd** [typed-graphql-builder/typed-graphql-builder#42]
Thanks for a great library. I've been looking for something exactly like this to replace codegen in watch mode.

Is it possible to set the operationName for a given operation? I'm not seeing the option exposed poking around the generated comment. Workaround for now is to manually edit the returned graphql document

**Comment by spion** [comment]
What would be an ergonomic API to do this? We can try overloads for `query`, `mutation` and `subscription` and if they cause problems with type inference (probably not but just in case) we can try `namedQuery`, `namedMutation`, `namedSubscription`

Also, mind if I ask - is this mainly to improve debugging, or are there other uses of the name?

**Comment by awinograd** [comment]
@spion yes the idea is primarily helpful for debugging and monitoring. I use apollo studio to be able to break down server performance by operation and it uses operationName to identify operations in the UI. I'm not sure what happens if no operationName is provided, but I would imagine it becomes harder to know where the query originated in the app.

**Comment by awinograd** [comment]
What do you think about this for an API?

```ts

type QueryOptions = {
  operationName?: string;
}

function query<Sel extends Selection<$RootTypes.query>>(
  selectFn: (q: $RootTypes.query) => [...Sel],
  options?: QueryOptions;
) {
}
```

**Comment by spion** [comment]
I like that its guaranteed to avoid issues with type inference.

I was thinking something that looks more like GraphQL syntax

```typescript
query('MyQueryName', q => [
  q.field({arg: 1}, f => [
    f.id, 
    f.name
  ])
]);
```

i.e. if the first argument is a string, its treated as an operation name.

I think we should give that one a try first as it mimics GraphQL more closely - if there are issues, the `options` argument seems like a rock-solid (as well as more extensible - although not sure if that's needed?) alternative.

**Comment by awinograd** [comment]
i agree your syntax is more graphql like. I also cannot foresee any other options we'd need to add. Would be nice to support that syntax as a function overload vs totally removing the current API if no operation name is needed

**Comment by spion** [comment]
Overloads seem to be working just fine :grinning:
