### ISSUE TITLE
generated client incompatible with noUnusedLocals/noUncheckIndexedAccess tsconfig options

### ISSUE THREAD

**Issue by awinograd** [typed-graphql-builder/typed-graphql-builder#44]
`noUnusedLocals` and `noUncheckedIndexedAccess` must be `false` otherwise the generated client file produced typescript errors

**Comment by spion** [comment]
Hi :wave:

Let me know if #45 addresses this for you.

**Comment by awinograd** [comment]
@spion #45 works perfectly with my tsconfig. Thanks for putting a fix together so quickly
