### ISSUE TITLE
Best Practice for unions (__typename support?)

### ISSUE THREAD

**Issue by awinograd** [typed-graphql-builder/typed-graphql-builder#59]
I'm using typed-graphql-builder with union types in tests as follows:

```ts
      const result = await client.request(
        mutation((m) => [
          m.performMutation({ input: $('input') }, (y) => [
            y.$on('Success', (p) => [p.id]),
            y.$on('Error', (p) => [p.message]),
          ]),
        ]),
      );
      
      // TSError: Property 'id' does not exist on type { id: string } | { message: string }
      expect(result.performMutation.id).toBeTruthy();
```

Currently I'm not able to access properties on the result without using an `'in`' clause, e.g.

```ts
      if (!('id' in result.performMutation)) {
        throw new Error('Error: ' + result.signupYSTYouth.message);
      }
```

It's a little more cumbersome than being able to add `__typename` on both union objects and switching:

```ts
if (result.performMutation.__typename === 'Success') {
   // ...
} 
```

Is the `'in'` operator the suggested best practice for refining union types? If not, is there another path forward you could recommend?

**Comment by spion** [comment]
The cli should have an `includeTypename` option, does that help?

**Comment by awinograd** [comment]
@spion I missed that options. Apologies for the noise here... it works great

**Comment by awinograd** [comment]
@spion i'm now noticing that `includeTypename` adds `__typename` to input types as well. The field is optional so it's not blocking anything, but I dont think that's desired behavior

**Comment by homoky** [comment]
Please, could we add this to readme?
