### ISSUE TITLE
Inconsistent type-checking for input arguments

### ISSUE THREAD

**Issue by michaelbridge** [typed-graphql-builder/typed-graphql-builder#66]
In both cases, `junk` is an invalid argument, while `id` is valid. As you can see in the 2nd example, type-checking does not correctly identify `junk` as an invalid parameter. This issue also exists within more complicated JSON inputs, but this is the simplest reproduction.

![Screen Shot 2023-12-15 at 4 12 05 PM](https://github.com/typed-graphql-builder/typed-graphql-builder/assets/6562899/2d2ea4b5-b4ef-4719-a091-743b3495db25)

The generated type is as follows:

```
company<Args extends VariabledInput<{
    id: number,
}>, ...
```

I experimented with several solutions but have thus far been unsuccessful.  The solution I thought would work did not -- this involves wrapping `VariabledInput` with `Exact` (per [type-fest](https://github.com/sindresorhus/type-fest/blob/main/source/exact.d.ts)):

```
company<Args extends Exact<VariabledInput<{
    id: number,
}>, Args>, ...
```

Thoughts? Hints? Suggestions?

**Comment by spion** [comment]
Unfortunately not much I can do - `Args extends VariabledInput<argsType>` is necessary to be able to accept variables in any position of argsType, however, `extends` also implies "additional properties available".

An alternative design that I was playing with but never got a chance to make work

```typescript
query<{myVar: string}>('QueryName', (q, vars) => [
  q.company({id: vars.myVar}, c => [c.display_name, c.investments(all)])
])
```

Runtime details: a proxy is passed where any get accessor always returns a variable (with the name of the accessor)

Pros
- no need for generics, it can simply be VariabledInput<inputType>
- no more problems with infinite recursion for some complex (e.g. Hasura) types
- much simpler generated code

Cons
- slightly more verbose
- slightly weirder
- probably no type inference
- need to import the right input type (including scalars) when writing queries.
- large, backward incompatible change in the design

**Comment by spion** [comment]
Looks like I was wrong

```
continent<
    Args extends VariabledInput<{
      code: string
    }>,
    Sel extends Selection<Continent>
  >(
    args: Args & { [K in keyof Args]: K extends keyof { code: string } ? Args[K] : never },
    selectorFn: (s: Continent) => [...Sel]
  )
```

has the desired behavior. Haven't tried yet if it will work in all situations.

**Comment by spion** [comment]
PR: https://github.com/typed-graphql-builder/typed-graphql-builder/pull/67
