### ISSUE TITLE
Query Execution Example without Appollo Client 

### ISSUE THREAD

**Issue by egloffmark** [typed-graphql-builder/typed-graphql-builder#77]
Dear all, would it be possible to show an example how the query builder and execution of queries and retrieval of a typed reponse can be done without Apollo Client or React libraries? Just with a plain "fetch" example?  Thank you

**Comment by spion** [comment]
You can use https://github.com/jasonkuhrt/graphql-request

I'm afraid its a bit tricky to use fetch directly - the result of typed graphql builder is a query document object (with AST) rather than a string, which is typically what is expected by client libraries.

**Comment by spion** [comment]
If you omit the `:any` type annotations, it should work.

Replit example: https://replit.com/@spion/TypedGraphqlBuilderRequestExample#index.ts

**Comment by egloffmark** [comment]
Thank you, is it also possible to retrieve it as "country" Object ? means instead of 
```
const countriesQuery = query((q) => [
  q.countries((c) => [c.name({ lang: "en" }), c.capital, c.code]),
]);
```
something like that it returns c as type "country"?
```
const countriesQuery = query((q) => [
  q.countries((c) => c),
]);
```

**Comment by spion** [comment]
There should be an `all` helper to get all fields - unforutunately its not documented yet.

**Comment by spion** [comment]
I wrote something here https://typed-graphql-builder.spion.dev/docs/query-syntax/fields
