### ISSUE TITLE
usage with libraries

### ISSUE THREAD

**Issue by spion** [typed-graphql-builder/typed-graphql-builder#8]

**Comment by jakobo** [comment]
Volunteering to take on the urql bit as we're using tgqlb with urql here at work. There's no custom code requirements if using the library-libraries (`@urql/*`) or the core lib (@urql/core).

Looks like the PR would target https://github.com/typed-graphql-builder/documentation/tree/main/docs/clients, correct?

**Comment by spion** [comment]
Sounds good :+1:  

Yep, currently the documentation is in the other repo, and that's indeed the correct location.
