### ISSUE TITLE
OutputTypeOf<T> returns never when T is an interface type

### ISSUE THREAD

**Issue by dheardal** [typed-graphql-builder/typed-graphql-builder#83]
I would expect in this case OutputTypeOf<T> returns all fields that are on the interface, however it returns never.

**Comment by spion** [comment]
Thanks for noticing the issue. I've opened 84 which should hopefully address it.

The output type will behave similarly to a union and include a __typename discriminator as well as all fields. Given that unions and interfaces can both be similarly queried using `$on` this should make sense. Let me know if this sounds good.

**Comment by dheardal** [comment]
Yep makes sense, thanks for fixing
